### PR TITLE
Make brotli optional

### LINKED ISSUE #202: Harder to install 0.16.0 due to dependency on brotli-size
Hi! Thank you for a great tool :-)

**Do you want to request a *feature* or report a *bug*?**
Ease of use regression between 0.15.3 and 0.16.0.

**What is the current behavior?**
#194 (released in 0.16.0) added support for tracking the brotli sizes of files, however to do so it had to add a dependency on [brotli-size](https://www.npmjs.com/package/brotli-size), which itself has a dependency on [iltorb](https://www.npmjs.com/package/iltorb). 

If iltorb isn't able to find a pre-compiled binary, it has to build using node-gyp, which requires Python and g++ be installed - which often aren't in Docker images, or in Windows environments.

For users that aren't making use of the brotli size feature, it would be a shame to have to install Python/g++ just to allow bundlesize to install. Perhaps `brotli-size` could be made an optional dependency?

It's worth also noting that:
* compiled dependencies are pretty painful at the moment even when they succeed, due to yarnpkg/yarn#932
* the `brotli-size` dependency doubled the install size and package dependency count of bundlesize (taking it up to ~200 dependencies!)
* iltorb currently doesn't work with repositories that are using the `no-bin-links` feature (necessary when using npm/yarn inside a linux Vagrant environment using shared folders with a Windows host). I'll be filing an issue against iltorb shortly for this. _Edit: filed MayhemYDG/iltorb#58_

**If the current behavior is a bug, please provide the steps to reproduce.**
`docker run --rm -it node:9-slim yarn add bundlesize@0.16.0 --dev`
...which results in: https://emorley.pastebin.mozilla.org/9078461

**What is the expected behavior?**
Successful install, like with 0.15.3:
`docker run --rm -it node:9-slim yarn add bundlesize@0.15.3 --dev`
...which results in: https://emorley.pastebin.mozilla.org/9078471

**Please mention other relevant information.**
- node version: 9.6.0
- npm version: N/A (yarn 1.3.2)
- Operating system: Multiple (but Debian jessie for the example above)
- bundlesize version: 0.16.0

### PR DESCRIPTION
**Pull request by siddharthkp**
## Motivation and Context

From the looks of it, `iltorb`'s native bindings are large + don't play well on all platforms - and fails installs on windows and some CI environments.

1. For folks not using brotli compression at all, this is unnecessary overhead.
2. Native brotli compression support landed in node 10.16.0 (LTS), we don't need to include an external dependency for that
3. For folks using brotli and node < 10.16.0, this PR **is a breaking change** and will ask them to install `bundlesize-plugin-brotli` to continue

Changes introduced in this PR:

1. Remove `brotli-size` from dependencies

2. On Node >= 10.6.0, use `zlib.brotliCompressSync`

3. On Node < 10.6.0, ask to install `bundlesize-plugin-brotli`

4. Introduces `bundlesize-plugin-brotli`

Fixes #202, #283 and #213

Prior work: #220 #299

### CODE REVIEW

**Comment by siddharthkp** [comment]
### Open questions

- Should we merge this now or wait for 1.0.0 because of the breaking change?

**Comment by Haroenv** [comment]
I guess it depends how many things we want to change still in a v1, I think it's a breaking change as well

**Comment by siddharthkp** [comment]
> I guess it depends how many things we want to change still in a v1, I think it's a breaking change as well

True, might make sense to keep them all in a branch and release together.

**Comment by anikethsaha** [comment]
> ### bundlesize-plugin-brotli

@siddharthkp  You are making bundlesize plugable? if so, its just **AWESOME** 

Plugins are the kind of best suites for Scalability.

**Comment by siddharthkp** [comment]
Merged into [beta](https://github.com/siddharthkp/bundlesize/pull/324) channel

**Comment by thomaswelton** [comment]
It also looks like brotli size has been updated to drop `iltorb`
https://github.com/erwinmombay/brotli-size/commit/8ca8a27330ddeba1d19dd1c21ab521a884f0deac

Is there a roadmap for release of your beta?

**Comment by siddharthkp** [comment]
Hi! 

You might want to use this version of bundlesize that solves this issue: https://github.com/siddharthkp/bundlesize2#migration-from-bundlesize0180

it's not feature complete, but you might not need the missing features at all.

**Pull request merged**
