### PR TITLE
Fix README.md: filename extension should be json instead of js

### PR DESCRIPTION
**Pull request by christineoo**
## Description

Fix README.md. The example in the README.md is specifying the filename as `bundlesize.config.js` but it should be `bundlesize.config.json`.

Please review and merge. Thanks~!

### CODE REVIEW

**Comment by Haroenv** [comment]
Looks like it's correct though https://github.com/siddharthkp/bundlesize/blob/86b58c8c57316ab1c0a60e17251a66007062a011/src/config.js#L9

**Comment by christineoo** [comment]
Thanks for the quick review~! 

Yes, the acceptable configuration paths are `package.json` and `bundlesize.config.json`.  Currently, the readme is specifying the **file extension** of `bundlesize.config` file as `.js`  which is incorrect. 

```diff
- 2. `bundlesize.config.js`
+ 2. `bundlesize.config.json`
```

Hope my understanding is correct 🤔💭

**Comment by palashmon** [comment]
Yes, you're right. **`README.md`** is actually specifying the filename as `bundlesize.config.js`. I think we should merge this PR.

**Comment by siddharthkp** [comment]
Good catch! Thanks!

**Comment by Haroenv** [comment]
oops, sorry for the confusion

**Pull request merged**
