### PR TITLE
Travis CI: Node.js 8 is end of life

### PR DESCRIPTION
**Pull request by cclauss**
https://github.com/nodejs/Release

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- My code follows the code style of this project.
- If my change requires a change to the documentation I have updated the documentation accordingly.
- I have read the **CONTRIBUTING** document.
- I created an issue for the Pull Request

### CODE REVIEW

**Comment by siddharthkp** [comment]
Can you change this to the oldest supported node version?

**Comment by cclauss** [comment]
Sure...  Let's see if Travis passes this one first and then I will drop it back to v10.

https://github.com/siddharthkp/bundlesize#build-status-for-github talks about other CI systems but has someone gotten this working with GitHub Actions?  They provide a `$GITHUB_TOKEN` secret.
https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow

**Comment by siddharthkp** [comment]
I have seen some examples in the wild. But don't have it handy

**Comment by cclauss** [comment]
Tests pass on:
```
$ node --version
v15.4.0
$ npm --version
7.0.15
$ nvm --version
0.37.0
```

Dropping back to Node.js 10 which has an end of life on 2021-04-30.

**Pull request merged**
