### PR TITLE
feat: Add compression option (gzip|brotli|none)

### LINKED ISSUE #139: Flag to disable gzip
**Feature**

***What is the current behavior?***

`maxSize` is max size of gzipped files.

***What is the expected behavior?***

Bundlesize can be used not only for checking assets size. Sometimes it could be helpfull if we have option like `maxRealSize`.

```
fs.statSync(path).size
```

### PR DESCRIPTION
**Pull request by FezVrasta**
## Description

Added a `-c` or `--compression` option that accepts `gzip`, `brotli` or `none`

## Motivation and Context

This fixes #139 and also implements the brotli compression.

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist:

- My code follows the code style of this project.
- If my change requires a change to the documentation I have updated the documentation accordingly.
- I have read the **CONTRIBUTING** document.
- I created an issue for the Pull Request

### CODE REVIEW

**Comment by SvanBoxel** [comment]
What kind of input do you need in order to get this PR approved? :)

**Comment by siddharthkp** [comment]
1. just needs some testing
2. I'm happy to disable codeclimate, would take some technical debt for now until I find a chunk of time to fix it.

I'm having trouble coming back to bundlesize because I'm not using it on the current project I'm working on (yet)

If you can give me a hand in testing it, we can merge this!

**Comment by SvanBoxel** [comment]
Hey @siddharthkp, I created a new PR (didn't have access to this one) that meets the requirements. (Updated tests, docs and reporter output). Please check it out. https://github.com/siddharthkp/bundlesize/pull/194

**Comment by siddharthkp** [comment]
Carried forward in https://github.com/siddharthkp/bundlesize/pull/194

**Comment by siddharthkp** [comment]
Published as `0.16.0`

**Pull request closed without merging**
