### PR TITLE
feat: implement glob pattern path mapping to master

### PR DESCRIPTION
**Pull request by kanzelm3**
## Description

I have implemented a mechanism to map paths with dynamic glob patterns correctly to their corresponding file on the master branch. This change should not be a breaking change, and 0 configuration changes are necessary to implement it. It will just work if you are already using dynamic glob patterns today.

I brought the [micromatch](https://github.com/micromatch/micromatch) library into the project in order to facilitate breaking down the glob search into it's individual segments (or match groups if you want to put it in regex terms).

## Motivation and Context

Resolves https://github.com/siddharthkp/bundlesize/issues/208

#### Example output _without_ my changes

screen shot 2018-04-04 at 3 43 54 am

#### Example output _with_ my changes

screen shot 2018-04-04 at 3 44 30 am

## Types of changes

- New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by siddharthkp** [comment]
Hey, thanks for the feature!

I'm tied up with a few things right now, I'll be able to have a look at this sometime next week 

Cheers

**Comment by kanzelm3** [comment]
@siddharthkp ok, let me know if there is anything I can do to make the review easier on you.

I would have added tests but there is not really a good foundation set up for that. It looked like there was some work being done on that here https://github.com/siddharthkp/bundlesize/pull/174 but that PR is old and hasn't been touched in a while.

I would love to help implement a unit testing framework if that is something you would be interested in. It would be nice to have tests for various glob patterns to ensure that they get mapped properly and when people want to make changes, they can have somewhat of a guarantee that what they changed didn't break any of the existing functionality.

**Comment by kanzelm3** [comment]
Any updates on this?

**Comment by siddharthkp** [comment]
Hey! Sorry I was on a laptop less vacation.

Will test this out soon

**Comment by iam4x** [comment]
Gentle reminder, any update on this one? @siddharthkp

**Comment by rmccue** [comment]
I'd be super interested in this, so if there's anything blocking here, happy to contribute!

**Comment by abernix** [comment]
This is a nice zero-configuration solution, but for the case where there isn't a static portion of the filename (at all!), I feel like it would be useful to have the concept of a _named group_ where the byte total of the globbed files within a path only counted against the named-group's relative change/delta.  For example:

```json
  "bundlesize": [
    {
      "name": "partners",
      "path": "./build/partners/**/*.js",
      "maxSize": "400 kB"
    },
    {
      "name": "admin",
      "path": "./build/admin/**/*.js",
      "maxSize": "400 kB"
    }
  ],
```

All of the files within the `/admin/` or `/partners/` directory could change, but `bundlesize` would look at the total bytes within that glob (i.e. `du -ks ./build/admin/**/*.js`) count them against its previous known sum for `admin`.  This would also be a nice configuration surface which could provide a more familiar name to the viewer of a PR, who may be less familiar with the bundling technique at play (for example, what a `dist.js` is!).

Thoughts?

**Comment by TimonVS** [comment]
@siddharthkp Sorry to bother you with this, but is there any way I could help out to get this merged? It would be tremendously beneficial for everyone using `chunkhash` for their filenames (so including all users of create-react-app).

**Pull request closed without merging**
