### PR TITLE
Upgrade axios, github-build dependencies

### PR DESCRIPTION
**Pull request by poojagunturu96**
## Description

Upgraded `axios` dependency as the current version has a security vulnerability. Upgraded `github-build` as well, as `github-build` depended on the vulnerable version of `axios`.

## Motivation and Context
Fix for #380.

## Types of changes
- Dependency upgrade (non-breaking change which fixes an issue)

## Checklist:

- My code follows the code style of this project.
- If my change requires a change to the documentation I have updated the documentation accordingly.
- I have read the **CONTRIBUTING** document.
- I created an issue for the Pull Request

### CODE REVIEW

**Comment by ruZZintl** [comment]
@siddharthkp please merge this and create a new release. It addresses https://github.com/advisories/GHSA-wf5p-g6vw-rhxx

**Comment by ruZZintl** [comment]
ETA? Any reason to not merge this? If not, please merge and release. Thanks.

**Comment by ruZZintl** [comment]
@siddharthkp is this repo being maintained?

**Comment by loftshed** [comment]
@siddharthkp just want to add myself to the crowd requesting this lil dependency bump, if you ever get the time it would be very appreciated 🥺

**Comment by siddharthkp** [comment]
Released as bundlesize@0.18.2

**Comment by loftshed** [comment]
@siddharthkp Thank you!! :)

**Pull request merged**
