### PR TITLE
Add Unit- and Integration Tests

### PR DESCRIPTION
**Pull request by Furizaa**
Some aspects of the tool are hard to test (like the push to the API or the CI env variables). It would be nice to have automated tests for this.

This PR adds a buttload of unit tests while it also decouples the code to make testing easier. This would now also enable a rally easy integration of https://github.com/siddharthkp/bundlesize/issues/9. A list of tests can be seen here:

https://travis-ci.org/siddharthkp/bundlesize/builds/249366081

Tests found in `__tests__/integration` test the whole process including the calls to the API and github. These packages are mocked away so no real requests are made.

This is as far as I came until now. Adding the missing test files should be straight forward. A merge would be nice regardless of that because I don't know when I will find the time to add the missing tests and keeping this PR up-to-date would be a hassle. 

- [x] integration/ci
- [x] integration/cli (incl. api, github)
- [x] environment-test
- [x] parser-test
- [x] runner-test
- [ ] api-tests
- [ ] files-test
- [ ] reporter-test

### CODE REVIEW

**Comment by siddharthkp** [comment]
@Furizaa I'm totally up for the idea of adding tests.

Unfortunately, I haven't got time to go through the changes. Soon!

**Comment by Furizaa** [comment]
Thanks, take the time you need. Just keep in mind that it's hard to keep up with other changes 😅 Things like the threshold/maxSize thingy are easy to merge. But the first bigger change will be much harder.

**Comment by siddharthkp** [comment]
@Furizaa Will make sure I merge tests before making any big changes!

**Comment by siddharthkp** [comment]
Hey, thanks again for writing these!

I'm a little busy this week. I will test and merge this early next week.

**Comment by siddharthkp** [comment]
Merging this to a temporary branch

**Comment by siddharthkp** [comment]
@Furizaa Hey sorry, I don't understand a lot of changes made here. So I'm going to go ahead with the other pull requests and then come back to this one.

You wouldn't have to back merge, i'll take of it 😄

**Pull request merged**
